EO_SUBJECTS = "http://id.nrk.no/2016/mdb/relation/subjects"
EO_CATEGORIES = "http://id.nrk.no/2016/mdb/relation/categories"
EO_LOCATIONS= "http://id.nrk.no/2016/mdb/relation/locations"
EO_SPATIALS = "http://id.nrk.no/2016/mdb/relation/spatials"
EO_CONTRIBUTORS = "http://id.nrk.no/2016/mdb/relation/contributors"
REL_REFERENCES = "http://id.nrk.no/2016/mdb/relation/references"
REL_ITEMS="http://id.nrk.no/2016/mdb/relation/items"
REL_DOCUMENTS="http://id.nrk.no/2016/mdb/relation/documents"